### ISSUE TITLE
User Story 14: "Admin User" CRUD: Admin can edit Users profile

### ISSUE THREAD

**Issue by geoffreyadebonojo** [jordanwa1947/little_shop#22]
As an admin user
When I visit a user's profile page ("/users/5")
And I click the link to edit a user's profile data
The same behaviors exist as if I were that user trying to change their own data
Except I am returned to the show page path of "/users/5" when I am finished

**Comment by jordanwa1947** [comment]
Issue: after editing a user's show path,  the admin is take to their own profile path rather than the user's.

**Comment by DanHutch** [comment]
I am happy to fix this if you want?
if so can you push to a branch so i can pull from there and work on it?

**Comment by jordanwa1947** [comment]
Sounds good man. It's actually already pushed and Geoff and I were discussing the issue earlier.

**Comment by DanHutch** [comment]
wait so should i not mess with it?

**Comment by jordanwa1947** [comment]
No, it's good, The story I had done just require an edit link, so I just gave it the one from when a user edits, so it acts like a user editing even though it's an admin. Look a the user controller and it redirects to the profile page of the editor.

**Comment by DanHutch** [comment]
im not understanding very well. is this an issue still or is it resolved?

**Comment by jordanwa1947** [comment]
sorry man, it is an issue. When I say you're good, I mean go ahead with fixing it because the admin should be redirected to the user's show page after the user info is updated.

**Comment by DanHutch** [comment]
okay. can you please respond over slack instead of here this is cumbersome and i am trying to get a couple answers quickly before i can work on this. thanks
